---
output:
  sort-results: true
linters:
  # List of *non-default* linters to enable
  enable:
    - asciicheck  # Check that your code does not contain non-ASCII identifiers
    - bidichk  # Checks for dangerous unicode character sequences
    - bodyclose  # Checks whether HTTP response body is closed successfully
    - errorlint  # Checks for error wrapping scheme issues in Go >= 1.13
    - gocognit  # Computes and checks the cognitive complexity of functions
    - gocritic  # Checks for bugs, performance and style issues
    - gofmt  # Checks whether code was gofmt-ed. Uses '-s' simplification option
    - gomnd  # An analyzer to detect magic numbers
    - gosec  # Inspects source code for security problems
    - ifshort  # Checks that your code uses short syntax for if-statements
    - misspell  # Finds commonly misspelled English words in comments
    - revive  # Drop-in replacement of golint
    - tenv  # Detects using os.Setenv instead of t.Setenv since Go1.17
    - unconvert  # Remove unnecessary type conversions

linters-settings:
  errcheck:  # Enabled by default
    # report not checking of errors in type assertions: `a := b.(MyStruct)`;
    check-type-assertions: true
    # report assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    check-blank: true

  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10

  gosimple:  # Enabled by default
    go: "1.18"

  gosec:
    excludes:
      # Potential HTTP request made with variable url. The URL of the cloud controller API
      # is indeed variable by design. The URL must be given to watchtower, where it will
      # proceed to make requests to determine the state of the environment.
      - G107
